-- Update legal content with full existing content from the pages
UPDATE public.legal_content 
SET content = '<div class="prose prose-lg max-w-none"><section><h2 class="text-2xl font-bold text-primary mb-4">1. DEFINICIONES</h2><ul class="list-disc pl-6 space-y-3"><li><strong>Plataforma:</strong> Se refiere al sitio web www.tuconsultorlegal.co y todas sus funcionalidades.</li><li><strong>Usuario:</strong> Toda persona natural o jurídica que accede y/o utiliza los servicios de la Plataforma.</li><li><strong>Lexi (Asistente de IA):</strong> La herramienta de inteligencia artificial de la Plataforma que interactúa con el Usuario.</li><li><strong>Servicios:</strong> Incluye la generación de documentos legales y la prestación de asesoría jurídica inicial.</li><li><strong>Revisión Humana:</strong> El proceso mediante el cual un abogado humano revisa y aprueba el documento generado por IA.</li></ul></section><section><h2 class="text-2xl font-bold text-primary mb-4">2. NATURALEZA Y ALCANCE DEL SERVICIO</h2><p class="font-semibold mb-4">Queremos ser completamente transparentes sobre cómo funcionamos:</p><h3 class="text-lg font-bold mb-2">Servicio de Información y Asistencia Tecnológica</h3><p class="mb-4">El Usuario reconoce que Lexi no es un abogado. Lexi es una herramienta tecnológica para generar borradores basados en plantillas.</p><h3 class="text-lg font-bold mb-2">No es Asesoría Jurídica Instantánea</h3><p class="mb-4">La información proporcionada por Lexi es preliminar. Las decisiones legales no deben basarse únicamente en ella.</p><h3 class="text-lg font-bold mb-2">La Importancia de la Revisión Humana</h3><p>El servicio se perfecciona cuando ha pasado por Revisión Humana. El documento final validado es nuestra responsabilidad profesional.</p></section><section><h2 class="text-2xl font-bold text-primary mb-4">3. OBLIGACIONES DEL USUARIO</h2><ul class="list-disc pl-6 space-y-2"><li>Ser mayor de edad y tener capacidad legal para contratar.</li><li>Proporcionar información veraz y precisa.</li><li>Utilizar la Plataforma para fines lícitos.</li><li>Custodiar la confidencialidad de sus credenciales.</li></ul></section></div>',
    title = 'Términos y Condiciones de Uso',
    last_updated = now()
WHERE page_key = 'terms-and-conditions';

UPDATE public.legal_content 
SET content = '<div class="prose prose-lg max-w-none"><section><h2 class="text-2xl font-bold text-primary mb-4">1. RESPONSABLE DEL TRATAMIENTO</h2><p class="mb-4">El responsable del tratamiento de tus datos personales es:</p><ul class="list-disc pl-6 space-y-2"><li><strong>Razón Social:</strong> TU CONSULTOR LEGAL S.A.S.</li><li><strong>Domicilio:</strong> Envigado, Antioquia, Colombia</li><li><strong>Correo electrónico:</strong> contacto@tuconsultorlegal.co</li><li><strong>Sitio web:</strong> www.tuconsultorlegal.co</li></ul></section><section><h2 class="text-2xl font-bold text-primary mb-4">2. INFORMACIÓN QUE RECOPILAMOS</h2><p class="mb-4">Para prestar nuestros servicios, recopilamos:</p><ul class="list-disc pl-6 space-y-3"><li><strong>Datos de Identificación:</strong> Nombres, apellidos, cédula, fecha de nacimiento</li><li><strong>Datos de Contacto:</strong> Email, teléfono, domicilio</li><li><strong>Datos del Caso:</strong> Información relacionada con su situación legal</li><li><strong>Datos Técnicos:</strong> IP, dispositivo, navegador</li></ul></section><section><h2 class="text-2xl font-bold text-primary mb-4">3. TRATAMIENTO DE DATOS SENSIBLES</h2><p class="mb-4">Por la naturaleza de servicios legales, podría suministrarnos datos sensibles. Su autorización es voluntaria y explícita.</p></section><section><h2 class="text-2xl font-bold text-primary mb-4">4. FINALIDAD DEL TRATAMIENTO</h2><ul class="list-disc pl-6 space-y-3"><li><strong>Prestación del Servicio:</strong> Generar documentos y consultas solicitadas</li><li><strong>Revisión por Abogados:</strong> Compartir información con abogados para revisión</li><li><strong>Comunicación:</strong> Enviar documentos y notificaciones</li><li><strong>Facturación:</strong> Procesar pagos</li><li><strong>Mejora:</strong> Analizar datos para mejorar servicios</li></ul></section><section><h2 class="text-2xl font-bold text-primary mb-4">5. DERECHOS DEL TITULAR</h2><p class="mb-4">Tienes derecho a:</p><ul class="list-disc pl-6 space-y-2"><li>Conocer, actualizar y rectificar tus datos</li><li>Solicitar prueba de autorización</li><li>Ser informado sobre el uso de tus datos</li><li>Presentar quejas ante autoridades</li><li>Revocar autorización y solicitar supresión</li><li>Acceder gratuitamente a tus datos</li></ul></section></div>',
    title = 'Política de Privacidad y Tratamiento de Datos Personales',
    last_updated = now()
WHERE page_key = 'privacy-policy';