
INSERT INTO public.email_templates (template_key, template_name, subject, html_body, is_active)
VALUES
(
  'lawyer_journey_day1_tip',
  'Journey Día 1 - Tip de Primer Uso',
  '🚀 {{lawyer_name}}, usa tu primera herramienta IA hoy',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f8fafc;font-family:Arial,sans-serif"><div style="max-width:600px;margin:0 auto;padding:40px 20px"><div style="background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><div style="text-align:center;margin-bottom:30px"><div style="width:60px;height:60px;background:linear-gradient(135deg,#6366f1,#8b5cf6);border-radius:50%;margin:0 auto 15px;display:flex;align-items:center;justify-content:center"><span style="font-size:28px">🚀</span></div><h1 style="color:#1e293b;font-size:24px;margin:0">¡Bienvenido a Praxis Hub!</h1></div><p style="color:#475569;font-size:16px;line-height:1.6">Hola <strong>{{lawyer_name}}</strong>,</p><p style="color:#475569;font-size:16px;line-height:1.6">Tu cuenta ya está lista. Te hemos otorgado <strong style="color:#6366f1">5 créditos de activación</strong> para que explores nuestras herramientas de IA.</p><div style="background:#f0f0ff;border-radius:8px;padding:20px;margin:25px 0"><h3 style="color:#4f46e5;margin:0 0 10px">💡 Tip: Empieza con el Análisis Legal IA</h3><p style="color:#475569;font-size:14px;margin:0">Es la herramienta más popular. Sube un caso y obtén un análisis completo con jurisprudencia relevante en minutos.</p></div><div style="text-align:center;margin:30px 0"><a href="{{dashboard_url}}" style="background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:16px;display:inline-block">Explorar Herramientas IA</a></div><p style="color:#94a3b8;font-size:13px;text-align:center">Tus créditos de activación ya están disponibles en tu cuenta.</p></div><p style="color:#94a3b8;font-size:12px;text-align:center;margin-top:20px">© {{current_year}} Praxis Hub. Todos los derechos reservados.</p></div></body></html>',
  true
),
(
  'lawyer_journey_day3_nudge',
  'Journey Día 3 - Nudge Herramientas',
  '🤖 {{lawyer_name}}, tu primer análisis IA te espera',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f8fafc;font-family:Arial,sans-serif"><div style="max-width:600px;margin:0 auto;padding:40px 20px"><div style="background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><div style="text-align:center;margin-bottom:30px"><span style="font-size:48px">🤖</span><h1 style="color:#1e293b;font-size:24px;margin:10px 0 0">¿Aún no has probado la IA?</h1></div><p style="color:#475569;font-size:16px;line-height:1.6">Hola <strong>{{lawyer_name}}</strong>,</p><p style="color:#475569;font-size:16px;line-height:1.6">Llevas 3 días en Praxis Hub y aún no has utilizado ninguna herramienta. ¡No te pierdas lo mejor!</p><div style="background:#fefce8;border-left:4px solid #eab308;border-radius:0 8px 8px 0;padding:20px;margin:25px 0"><p style="color:#854d0e;font-size:14px;margin:0"><strong>Sabías que...</strong> Los abogados que usan IA en sus primeros 3 días tienen un 80% más de probabilidad de optimizar su práctica legal.</p></div><h3 style="color:#1e293b;font-size:18px">Herramientas que puedes probar:</h3><ul style="color:#475569;font-size:15px;line-height:2"><li>📄 <strong>Análisis de documentos</strong> con IA</li><li>⚖️ <strong>Predicción de casos</strong></li><li>📝 <strong>Generación de escritos</strong></li><li>🔍 <strong>Investigación jurídica</strong></li></ul><div style="text-align:center;margin:30px 0"><a href="{{dashboard_url}}" style="background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:16px;display:inline-block">Probar Ahora</a></div></div><p style="color:#94a3b8;font-size:12px;text-align:center;margin-top:20px">© {{current_year}} Praxis Hub. Todos los derechos reservados.</p></div></body></html>',
  true
),
(
  'lawyer_journey_day7_profile',
  'Journey Día 7 - Completar Perfil',
  '👤 {{lawyer_name}}, completa tu perfil y recibe créditos extra',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f8fafc;font-family:Arial,sans-serif"><div style="max-width:600px;margin:0 auto;padding:40px 20px"><div style="background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><div style="text-align:center;margin-bottom:30px"><span style="font-size:48px">👤</span><h1 style="color:#1e293b;font-size:24px;margin:10px 0 0">Completa tu perfil profesional</h1></div><p style="color:#475569;font-size:16px;line-height:1.6">Hola <strong>{{lawyer_name}}</strong>,</p><p style="color:#475569;font-size:16px;line-height:1.6">Ya llevas una semana con nosotros. Completar tu perfil profesional te da acceso a funcionalidades avanzadas y te hemos preparado un regalo:</p><div style="background:linear-gradient(135deg,#f0f0ff,#e8e0ff);border-radius:12px;padding:25px;margin:25px 0;text-align:center"><p style="font-size:36px;margin:0 0 10px">🎁</p><p style="color:#4f46e5;font-size:20px;font-weight:bold;margin:0">3 Créditos Bonus</p><p style="color:#6366f1;font-size:14px;margin:5px 0 0">Ya disponibles en tu cuenta</p></div><h3 style="color:#1e293b">¿Qué te falta por completar?</h3><ul style="color:#475569;font-size:15px;line-height:2"><li>📸 Foto de perfil profesional</li><li>📋 Especialidades legales</li><li>📞 Teléfono de contacto</li><li>🏢 Información de tu firma/despacho</li></ul><div style="text-align:center;margin:30px 0"><a href="{{dashboard_url}}" style="background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:16px;display:inline-block">Completar Perfil</a></div></div><p style="color:#94a3b8;font-size:12px;text-align:center;margin-top:20px">© {{current_year}} Praxis Hub. Todos los derechos reservados.</p></div></body></html>',
  true
),
(
  'lawyer_journey_day30_lastchance',
  'Journey Día 30 - Última Oportunidad',
  '💎 {{lawyer_name}}, 15 créditos gratis te esperan - última oportunidad',
  '<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head><body style="margin:0;padding:0;background-color:#f8fafc;font-family:Arial,sans-serif"><div style="max-width:600px;margin:0 auto;padding:40px 20px"><div style="background:#fff;border-radius:12px;padding:40px;box-shadow:0 2px 8px rgba(0,0,0,0.06)"><div style="text-align:center;margin-bottom:30px"><span style="font-size:48px">💎</span><h1 style="color:#1e293b;font-size:24px;margin:10px 0 0">Te extrañamos en Praxis Hub</h1></div><p style="color:#475569;font-size:16px;line-height:1.6">Hola <strong>{{lawyer_name}}</strong>,</p><p style="color:#475569;font-size:16px;line-height:1.6">Ha pasado un mes desde tu registro y no has podido aprovechar todo lo que Praxis Hub tiene para tu práctica legal. Queremos darte una última oportunidad especial:</p><div style="background:linear-gradient(135deg,#fdf2f8,#fce7f3);border:2px solid #ec4899;border-radius:12px;padding:25px;margin:25px 0;text-align:center"><p style="font-size:36px;margin:0 0 10px">🎁</p><p style="color:#be185d;font-size:24px;font-weight:bold;margin:0">15 Créditos Gratis</p><p style="color:#db2777;font-size:14px;margin:5px 0 0">Última bonificación especial</p></div><p style="color:#475569;font-size:16px;line-height:1.6">Con estos créditos podrás:</p><ul style="color:#475569;font-size:15px;line-height:2"><li>🔍 Realizar investigaciones jurídicas con IA</li><li>📄 Analizar documentos legales automáticamente</li><li>⚖️ Obtener predicciones de casos</li><li>📝 Generar borradores de escritos</li></ul><div style="text-align:center;margin:30px 0"><a href="{{dashboard_url}}" style="background:linear-gradient(135deg,#ec4899,#be185d);color:#fff;padding:14px 32px;border-radius:8px;text-decoration:none;font-weight:bold;font-size:16px;display:inline-block">Reclamar Mis Créditos</a></div><p style="color:#94a3b8;font-size:13px;text-align:center">Los créditos ya están en tu cuenta. Solo necesitas iniciar sesión.</p></div><p style="color:#94a3b8;font-size:12px;text-align:center;margin-top:20px">© {{current_year}} Praxis Hub. Todos los derechos reservados.</p></div></body></html>',
  true
);
